"""Initial migration.

Revision ID: bbe02848da35
Revises: 
Create Date: 2024-12-22 22:35:50.157245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbe02848da35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AdditionalServices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_type', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DigitalPricing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(length=255), nullable=False),
    sa.Column('field', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('item', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('NewsAccounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator', sa.String(length=255), nullable=False),
    sa.Column('publication', sa.String(length=255), nullable=True),
    sa.Column('coverage_in_person', sa.Integer(), nullable=True),
    sa.Column('coverage_remote', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=255), nullable=False),
    sa.Column('field', sa.String(length=255), nullable=False),
    sa.Column('followers', sa.BigInteger(), nullable=True),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('account', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('digitalpricing')
    op.drop_table('newsaccounts')
    op.drop_table('additionalservices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additionalservices',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('newsaccounts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('indicator', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('publication', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('coverage_in_person', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coverage_remote', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('region', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('platform', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('field', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('followers', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('identifier', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('account', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('digitalpricing',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cost', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('indicator', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('field', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('item', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('channel', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('NewsAccounts')
    op.drop_table('DigitalPricing')
    op.drop_table('AdditionalServices')
    # ### end Alembic commands ###
